version: '3.3'
services:
    db:
        image: postgres:10.0-alpine
        restart: always
        environment:
            POSTGRES_USER: postgres # same as default
            POSTGRES_DB: imagedock # default postgres
            POSTGRES_PASSWORD_FILE: /run/secrets/postgres-passwd
        ports:
            - 5432:5432
        volumes:
            # uncomment for persistence
            #- /srv/docker/postgresql:/var/lib/postgresql
              # temporary this will probably be broken for windows
            - ./db/init/:/docker-entrypoint-initdb.d
        secrets:
            - postgres-passwd
secrets:
    postgres-passwd:
        file: ./dbpass.txt
